<HTML>
<HEAD>
<TITLE>Format Data</TITLE>
</HEAD>
<BODY>
  <?php
    $data = "45.5 derajat Celcius";

    printf("Format d : %d <BR>\n", $data);
    printf("Format b : %b <BR>\n", $data);
    printf("Format o : %o <BR>\n", $data);
    printf("Format x : %x <BR>\n", $data);
    printf("Format X : %X <BR>\n", $data);
    printf("Format c : %c <BR>\n", $data);
    printf("Format s : %s <BR>\n", $data);
    printf("Format f : %f <BR>\n", $data);

  ?>

</BODY>
</HTML>
